### ISSUE TITLE
Implement modules SharedReact and SharedReactivedata

### ISSUE THREAD

**Issue by balat** [ocsigen/eliom#162]
Take inspiration from Eliom_csreact file (in branch sharedreact).

**Comment by Drup** [comment]
Notes from today's discussion: 

So, the feature goal is to implement the `R` module for html/svg on the *server* that would create an initial value on the server and a signal on the client (with the right initialization). 

- Here is the branch: https://github.com/ocsigen/eliom/tree/sharedreact
- Currently, tyxml's functor is not used, and it needs study to see how to use it, it seems not completely trivial.
- Needs to add `{shared{ <expr> }}` in expression position that would desugar to the pair `ocaml ( <expr>, {{ <expr>}})`. Also need ```type 'a shared_value = 'a * 'a client_value```.
- An equivalent of the `React.S` module should be reimplemented on ```'a shared_react = 'a * 'a React.S.t client_value```.
- When a previous page is already here and we reload the page, in order to keep all the signals working properly, we need to use the old signals (but update their values back to the one sent by the server). Currently, this is done by registering signals in a cache (see `Eliom_cscache`) manually. It may be possible to make that more automatic.
- There might or might not be a problem of flickering when the initial server value is replaced by the signal. For now it's not visible.

@balat: Did I forgot anything ?

**Comment by balat** [comment]
No it's ok.
Keeping the old value of signal is not really related to Eliom_cscache.
User will decide where the signal is stored (for example in the cache).
The main problem with current solution is that it is too easy to forget the
[~default] parameter to React.S.create (and quite boring to have to do so).

**Comment by vasilisp** [comment]
This is in master now, so closing. All @Drup's points are addressed, except reusing old signals, for which we offer no help at this time. Report more specific issues as needed.
