### ISSUE TITLE
Custom types for forms

### ISSUE THREAD

**Issue by paurkedal** [ocsigen/eliom#256]
Can we please get back a functional equivalent of `user_type_select` and friends in Eliom 5.0+?  The param type used in the forms is aliased to `Eliom_parameter_base.atom`, but in that module only the `params_type` admits user defined types.  Would it be acceptable to add a `TUserAtom` constructor for `params` holding converter pair and adding something like

```ocaml
val user : to_string: ('a -> string) -> of_string: (string -> 'a) -> 'a param
```

to the Form signature?  I'm naming things here just so I can send a pull request if you agree.

**Comment by vasilisp** [comment]
I removed these partly because the implementation was lacking, partly because I thought that they are not used much. A replacement is part of the plan (along with other `Eliom_parameter` improvements).

It is tricky though: `Eliom_form` is shared code, i.e., the forms can be generated on the client. In this case, implementations of `of_string` are needed both on the server and on the client, but the client cannot make sure that a compatible `of_string` is available on the server.

**Comment by paurkedal** [comment]
My current use was a few enum-style datatypes with mapped to selects in the UI.  I worked around them by using string parameters.

I can see the problem if these parameters are to be used in JS generated forms.  Would it not then be possible to only provide the function to define user type on the server side with a signature like:
```ocaml
val user : to_string: ('a -> string) ->
           of_string: (string -> 'a) ->
           to_string_cv: ('a -> string) client_value ->
           of_string_cv: (string -> 'a) client_value ->
           'a param
```

**Comment by paurkedal** [comment]
I realized, as you said, it isn't that simple.  The above does not give the client access to the type, unless it's in a shared section, in which case we couldn't prevent it from being in a pure client section.

So, good to hear that you already have a plan.
