### ISSUE TITLE
eliomc: cannot use a ppx preprocessor from the command line

### ISSUE THREAD

**Issue by vouillon** [ocsigen/eliom#273]
It is not possible to use a `ppx` preprocessor from the command line,  as the `-ppx` option is consumed by `eliomc`.

**Comment by vasilisp** [comment]
We can rename the current `-ppx` flag to `-eliom-ppx` (or something). This will break the projects that have switched to PPX. Alternatively, we can keep the current `-ppx` semantics and add another flag (e.g., `-ppx-cmd`). Preferences?

**Comment by pveber** [comment]
Random user opinion: I'd rather see the breaking change (with the usual migration path documentation) than having misleading option names (better be coherent with the rest of the ocaml toolchain).

**Comment by vouillon** [comment]
A third option is for `eliomc` to absorb the first `-ppx` option and pass the subsequent ones to `ocamlc`.

**Comment by Drup** [comment]
> A third option is for eliomc to absorb the first -ppx option and pass the subsequent ones to ocamlc.

I was actually convinced I did that. Apparently I did not ...

**Comment by sagotch** [comment]
FWIW, I prefer the breaking change, for the same reason than pveber.

**Comment by vasilisp** [comment]
I have a half-done patch following @vouillon's suggestion. I just need to fix `eliomdep` and `eliomdoc` in the same way.

**Comment by sagotch** [comment]
:+1: anything that work would be perfect ;-)

**Comment by agarwal** [comment]
I know there are bigger problems to solve, but I don't agree with the way this issue was resolved. Now the first occurrence of `-ppx` (if given without a value means one thing, and the remaining occurrences (which must be given with a value) mean something else. This is highly non-standard. It adds just a bit of extra confusion, but I feel we shouldn't add even a tiny bit of extra headache on a build process that is already maddening.

**Comment by pwbs** [comment]
@agarwal I concur. This is really weird.
