### ISSUE TITLE
Eliom_shared_content not linked in client-side

### ISSUE THREAD

**Issue by vouillon** [ocsigen/eliom#275]
Since the recent changes in TyXML, Eliom_shared_content generates client-values (for constant reactive attributes, I think). However, no module depends on Eliom_shared_content client-side. Thus, it is not linked in, and we get error messages: "Code generating the following client values is not linked on the client".

And it is not possible to force a dependency from outside of Eliom, as the cmi file is not packaged.

A possible fix is to force a dependency of Eliom_content on Eliom_shared_content client-side.

**Comment by vasilisp** [comment]
My attempt to force a dependency (with a `force_link` value referenced from outside) didn't help. We can in principle add a `unit -> ...` around attributes, but that involves `Eliom_content` as a whole.

@Drup, can we just add unit arguments to the constant attributes inside TyXML? That's safer for complicated instantiations of the functor.

**Comment by Drup** [comment]
I would rather avoid it, unless you really can't make it work at all.

**Comment by vasilisp** [comment]
It is not just a question of linking. If I add this line to `eliom_content.eliom`:

```
let _ = {int React.S.t{ React.S.const 32 }}
```

we get an additional line in the browser log. It is a problem of client values appearing at the toplevel (and not produced by functions) inside Eliom. I haven't gone very deeply on the matter, but I suspect supporting such client values might be non-trivial.

I have a TyXML branch and an Eliom branch (both named `fix-eliom-275`) that in combination solve the issue. @Drup, I would prefer to merge these for now. In the future,  TyXML can export a finer-grained interface with a separate type for constant attributes, so that a client of the functor like Eliom can treat these specifically. (That is useful in any case, e.g., to avoid useless `React.S.const x` signals.)

**Comment by Drup** [comment]
I don't understand, what's the problem with this line ? It should be supported just fine.

@vasilisp Just use stable tyxml for now.

**Comment by vasilisp** [comment]
"Should" be supported maybe, but it isn't. It leads to the following:

```
Code generating the following client values is not linked on the client:
5WxLvI1/1
```

It is not the right time for the runtime cleanup that would resolve the above.

> @vasilisp Just use stable tyxml for now. 

We will have to resolve such issues in batch, they don't just go away. In the interim, we will have to update numerous Jenkins configurations, and TyXML itself will be unusable, so it won't receive any testing.

**Comment by balat** [comment]
Do you have a solution for this?

**Comment by balat** [comment]
Any news? This bug makes it very difficult to work :/

**Comment by vasilisp** [comment]
No news. The fix has been there for a while, waiting to be merged :).

**Comment by Drup** [comment]
@vasilisp You didn't do any PR. I don't even see mention of a specific branch.
