### ISSUE TITLE
Remove PUT and DELETE services

### ISSUE THREAD

**Issue by vasilisp** [ocsigen/eliom#354]
Removing `PUT` and `DELETE` services would be very useful for cleaning up the `Eliom_service` and `Eliom_registration` API. It would be very nice to have a binary GET/POST distinction.

Does anybody use these? I much doubt that Eliom is good for RESTful APIs, and I also doubt that our support for `PUT` and `DELETE` is sufficiently developed (e.g., #288).

**Comment by Drup** [comment]
I disagree, I think it's important we have those (and it was requested when we didn't have them).

**Comment by darioteixeira** [comment]
I've never used this feature myself (it seems overkill to use Eliom for RESTful services), but I reckon that any users out there who depend on it will be livid if it's removed. Might be better to ask on the mailing list, no?

**Comment by Stargateur** [comment]
In my startup, we use it to create our API Restful. We need the PATCH method and OPTION method to be clean in the future. But they are missing in eliom !

Why you want remove feature like that ? For a true http server it's mandatory to handle all method.

**Comment by vasilisp** [comment]
Eliom is a fairly high-level web framework, not a web server. Providing nice abstractions involves focusing on a particular subset of the possible functionality that is needed for a class of applications. In this particular case, we strive to provide a typeful service interface, and encoding the specificities of all methods becomes a burden.

Anyway, I think a good compromise is to only provide GET and POST for attached coservices, as in 5c887d21a7e9179dd7f4006b6c998f4d51571412 . I doubt that coservices would be of any use for RESTful APIs. (But it is hard to avoid limitations on the other verbs, like imposing `raw_post_params`.)

**Comment by Stargateur** [comment]
> we strive to provide a typeful service interface, and encoding the specificities of all methods becomes a burden.

Yes ... but you still promote using Ocsigen as RESTful API...
   https://ocsigen.org/tuto/manual/rest
Where you write:
   This tutorial will show you how to create a simple, yet complete, REST API using JSON as the serialization format. 
The issue : It is not "complete". You don't provide the means to partially update a ressource   
... and for a RESTful API there are 4 basic operations necessary :
GET -> Retrieve resources
POST   -> create new element. already exists -> error
PUT    -> with an ID. Can create ... if you have the ID... or update EVERYTHING
PATCH  -> update some fields [*]
DELETE -> remove resource
So if you want to allow updating only a couple of fields you *NEED* PATCH.
Like so for instance:
PATCH https://www.googleapis.com/drive/v2/files/fileId
In the request body, supply the relevant portions of a Files resource, according to the rules of patch semantics.
SEE: https://developers.google.com/drive/v2/reference/files/patch
The PATCH is an important component of REST ! [*]
So important that I would think it should be part of the ocsigen core implementation.
OPTIONS - allowing introspection of possible commands on a resource - is very much in the spirit of REST as well, but ... less important, less "core" than the above 5 /basic/ REST operations.
No ?
[*]
The HTTP methods PATCH can be used to update partial resources.
A partial update is extremely vital to REST as the interface often treats with a single url objects with LOOOOOOTS of properties that you don't want to allow all to be updated via PUT !
See:
http://restcookbook.com/HTTP%20Methods/patch/
https://tools.ietf.org/html/rfc5789

**Comment by Tormen** [comment]
> I much doubt that Eliom is good for RESTful APIs,
> (it seems overkill to use Eliom for RESTful services)

Hmmm. I am really sad to hear that. Because I think eliom is perfectly suited to be the platform for building a RESTful service on ... and am in the middle of implementing a RESTful api based on eliom... :(

If you would want an ocaml based RESTful api ... how do you do without eliom supporting it ?

I think the possibility to serve a RESTful api to some clients and later expose the same functionality via an eliom web app makes perfect sense to me.

**Comment by darioteixeira** [comment]
> If you would want an ocaml based RESTful api ... how do you do without eliom supporting it ?

If your only API is RESTful, then you have plenty of light-weight options, including directly using Cohttp, Opium, Webmachine, etc.

> I think the possibility to serve a RESTful api to some clients and later expose the same functionality via an eliom web app makes perfect sense to me.

Well, if you're doing more than just a RESTful API, then yes, Eliom is the perfect platform for it.

**Comment by darioteixeira** [comment]
@Stargateur said:

> ... and for a RESTful API there are 5 basic operations necessary :
> GET -> Retrieve resources
> POST -> create new element. already exists -> error
> PUT -> with an ID. Can create ... if you have the ID... or update EVERYTHING
> PATCH -> update some fields [*]
> DELETE -> remove resource

In practice, it's not uncommon to overload the POST method to serve both POST and PATCH functions. Suppose you're creating a new user: call POST on `/users`.  If you're doing a partial update on user 10: call POST on `/users/10`.  There's no chance of conflict or confusion because one function is parameterless and the other is always parameterised.  Moreover, there's even a school of thought that says that PATCH is superfluous and should not be used...

**Comment by Tormen** [comment]
@darioteixeira : I appreciate the feedback !

Stays to hope that eliom won't remove support for REST ...

**Comment by paurkedal** [comment]
I also hope the REST facilities says.  I'm using it along with client-server services within the same application.  Technically the POST method could be used for all stateful operations, but it is rather inelegant.  Note for instance that PUT and DELETE requests are supposed to be idempotent, whereas POST is not, and that a DELETE request should not contain data.  Also, a HTTP proxy may handle the methods differently.

@darioteixeira In your example POST should not modify `/users/10` but create a new sub-item, say `/users/10/1`, and repeating it might create `/users/10/2`, etc.  On the other hand a put to `/users/10` should replace the entry, and repeating the same request should be a no-op.

**Comment by darioteixeira** [comment]
> @darioteixeira In your example POST should not modify /users/10 but create a new sub-item, say /users/10/1, and repeating it might create /users/10/2, etc. On the other hand a put to /users/10 should replace the entry, and repeating the same request should be a no-op.

Well, my point is that on a server without PATCH support, you have to bend the modern REST guidelines a bit and declare that a POST to `/users/10` is interpreted as an update. Bear in mind that PATCH is relatively recent, whereas the RESTful concept is much older. Therefore, for many years REST interfaces actually had to rely on these semantics, and even today they are not uncommon.

**Comment by vasilisp** [comment]
I rest my case :). I still don't like `PUT` and `DELETE` in the context of Eliom, but apparently they can't go away.

Note that I am planning to remove attached `PUT` and `DELETE` coservices (old `put_coservice` and `delete_coservice` methods): #359 . I don't think these are of any use (neither for REST, nor for the web), and retaining these would involve either lots of boilerplate (like in the original implementation) or weird typing. Let me know if that poses any problems.

**Comment by paurkedal** [comment]
I'm happy as long as they're supported just for regular services.  Hopefully that limits the code duplication elsewhere.

I think we can even make the argument that PUT and DELETE does not make sense for attached co-services.  For, if a DELETE succeeds (200), then the resource identified by the URL should be considered gone, so there is nothing left for the co-service to be attached to.  For PUT the argument is more subtle, but considering its idempotency, each subsequent co-service should do a full (re-)submission to the same object.  At best it could be used for a successful refinement, but since the preceding PUT should have submitted the result of that stage, the application would better fetch the current state of the object from its own storage rather than relying on the request state.
